language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xmldiff
install: 
    - pip install -r requirements.txt
    - python setup.py install
before-script:
    - git clone https://github.com/proycon/folia.git FoLiA
    - mv FoLiA ../
script:  
    - bash tests/test.sh
